dependencies:
  - name: elasticsearch
    version: 7.3.0
    condition: elasticsearch.enabled
  - name: kibana
    version: 7.3.0
    condition: kibana.enabled
    repository: file://./charts/kibana
  - name: fluent-bit
    version: 0.5.1
    condition: fluent-bit.enabled
